version: '3.8'

services:
  app:
    build: ./
    container_name: emc_lab_application
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: mysql:8
    restart: always
    container_name: emc_lab_database
    environment:
      MYSQL_DATABASE: emc_lab_database
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - emc_lab_project_database:/var/lib/mysql
    command: "--wait_timeout=28800 --interactive_timeout=28800 --max_connections=500"

volumes:

  emc_lab_project_database:
